# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [1]:
#create a list
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [3]:
#whats the type
type(my_list)

list

In [2]:
#what is dtype
my_list.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [4]:
#whats the shape
list.shape

AttributeError: type object 'list' has no attribute 'shape'

#### create an array
format: np.array()

In [5]:
#import numpy
import numpy as np

In [9]:
#create the array
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [10]:
#whats the type
type(my_array)

numpy.ndarray

In [12]:
#whats the shape - wide x tall
my_array.shape

(4,)

In [13]:
my_array.dtype

dtype('int64')

#### access elements of our new array

In [16]:
my_array

array([1, 2, 3, 4])

In [14]:
my_array[0]

1

In [15]:
my_array[-1]

4

#### slice the array

In [21]:
my_array

array([1, 2, 3, 4])

In [17]:
my_array[1:]

array([2, 3, 4])

In [18]:
my_array[:2]

array([1, 2])

#### create an array from 1 to 100

In [24]:
#np.array(?)
a = np.array(range(1, 101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
#access single element
a[0]

1

In [26]:
#slice the array! 
a[25:]

array([ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
a[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Create a 2D array

In [39]:
#build a list of lists
matrix = [[1,2,3],
[2,3,4],
[6,7,8],
[4,5,6]]
matrix

[[1, 2, 3], [2, 3, 4], [6, 7, 8], [4, 5, 6]]

In [29]:
type(matrix)


list

In [40]:
#turn it into an array! 
matrix_array = np.array(matrix)
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

In [33]:
#type
type(matrix_array)

numpy.ndarray

In [41]:
matrix_array.shape

(4, 3)

In [42]:
matrix_array.dtype

dtype('int64')

#### access elements

In [43]:
matrix_array[0]

array([1, 2, 3])

In [44]:
matrix_array[0][0]

1

In [45]:
matrix_array[0,0]

1

In [46]:
matrix_array[2,1]

7

### Descriptive Stats

In [47]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

#### using methods: the method is called on the numpy object
format: object.method()

In [48]:
a.min()

1

In [49]:
a.max()

100

In [52]:
a.mean(), a.std()

(50.5, 28.86607004772212)

In [51]:
a.sum()

5050

#### using functions: using numpy to call functions

In [54]:
max(a)

100

In [53]:
np.max(a)

100

In [214]:
np.std(a)

28.86607004772212

In [215]:
np.mean(a)

50.5

In [216]:
np.sum(a)

5050

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [57]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [64]:
#make list of booleans aka our mask
mask = [True, False, False, True]
mask

[True, False, False, True]

In [65]:
#combine them - return True values
my_array[mask]

array([1, 4])

In [66]:
sum(mask)

2

#### how else can we get our array of boolean values?

In [67]:
my_array

array([1, 2, 3, 4])

In [68]:
#write a conditional with the array
my_array == 4

array([False, False, False,  True])

In [78]:
mask = (my_array == 4)
mask

array([False, False, False,  True])

In [79]:
my_array[mask]

array([4])

In [77]:
mask = my_array > 2
mask

array([False, False,  True,  True])

In [81]:
mask.dtype

dtype('bool')

#### make and apply our boolean mask

In [485]:
#format: array_name [ list_of_booleans ]


In [84]:
mask2 = (matrix_array > 3)
mask2

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [86]:
matrix_array 

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

In [92]:
b = matrix_array + 1
b

array([[2, 3, 4],
       [3, 4, 5],
       [7, 8, 9],
       [5, 6, 7]])

In [88]:
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

In [93]:
mask3 = (my_array ==2) | (my_array == 4)
mask3

array([False,  True, False,  True])

In [94]:
my_array[mask3]

array([2, 4])

#### cool! can we just do it with a list instead of an array?

In [95]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [99]:
#create a array of booleans
my_list[] == 4

SyntaxError: invalid syntax (3024950477.py, line 2)

In [100]:
mask

array([False, False, False,  True])

In [101]:
#apply an array of booleans to a list
my_list[mask]

TypeError: only integer scalar arrays can be converted to a scalar index

#### let's bring it back to arrays and make them bigger

In [102]:
#array
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [106]:
#mask
mask = a >= 90
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [107]:
#boolean mask
a[mask]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### shortcut?

In [121]:
a[a>=90]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

### what if index value is not in matrix?

In [122]:
a==105

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

#### what if we wanted to check two conditions?

In [492]:
# note the parenthesis
# also note that we're using & instead of and


In [125]:
mask = (a > 5) & (a < 15)
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [126]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

#### what if we wanted the opposite of our mask?
NOT operator is ~

In [127]:
~mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [128]:
# the ~ notates the opposite of
a[~mask]

array([  1,   2,   3,   4,   5,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [130]:
a[~((a > 5) & (a < 15))]

array([  1,   2,   3,   4,   5,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [131]:
my_list

[1, 2, 3, 4]

In [135]:
#using a for loop
new_list = []
for i in my_list:
    new_list.append(i+1)
new_list

[2, 3, 4, 5]

In [137]:
#using a list comprehension
new_list2 = [i+1 for i in my_list]
print(new_list2)

[2, 3, 4, 5]


#### easy way: doing it with an array

In [138]:
my_array

array([1, 2, 3, 4])

In [139]:
#using vectorization operations
my_array + 1

array([2, 3, 4, 5])

### more operations

In [140]:
my_array * 2

array([2, 4, 6, 8])

In [141]:
my_array // 2

array([0, 1, 1, 2])

In [142]:
my_array ** 4

array([  1,  16,  81, 256])

In [144]:
my_array / 4 +  2

array([2.25, 2.5 , 2.75, 3.  ])

In [145]:
np.log(my_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### show us the speed

In [147]:
#make a really big array
big_array = np.array(range(1_000_000))
big_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [149]:
%%timeit

big_array ** 2

481 µs ± 6.01 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [152]:
#make a really big list
big_list = list(big_array)
big_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [155]:
%%timeit

[i ** 2 for i in big_list]

76.4 ms ± 432 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ways to create arrays

#### full of zeros

In [158]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### full of ones

In [159]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [168]:
len(np.ones(10_000))

10000

#### full of whatever you want 

In [160]:
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [169]:
np.full(10, True)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [170]:
np.full(10, "Hi!")

array(['Hi!', 'Hi!', 'Hi!', 'Hi!', 'Hi!', 'Hi!', 'Hi!', 'Hi!', 'Hi!',
       'Hi!'], dtype='<U3')

#### a quicker way to make a range

In [177]:
aa = np.arange(1,10,2)
bb = np.arange(8,18,2)
print(aa,bb)

[1 3 5 7 9] [ 8 10 12 14 16]


In [180]:
ab = aa, bb
ab

(array([1, 3, 5, 7, 9]), array([ 8, 10, 12, 14, 16]))

#### an array of random integers

In [184]:
x = np.random.randint(1,10)
x

6

#### an array of random numbers from the standard distribution

In [185]:
np.random.randn(10)


array([ 0.22366868, -1.30878278,  0.3357212 , -0.85165649, -1.57333823,
       -1.37689366, -0.19106711, -0.23268591, -1.66786237, -1.45359408])

In [187]:
np.random.randn(10_000_000).mean()

-0.0001269855579972017